attr(dataset$camp_name, "label") <- "Название организации отдыха"
attr(dataset$date_in, "label") <- "Дата заезда"
attr(dataset$date_out, "label") <- "Дата выезда"
attr(dataset$session, "label") <- "Смена"
attr(dataset$region, "label") <- "Регион"
attr(dataset$duration, "label") <- "Продолжительность смены"
attr(dataset$family_visits, "label") <- "Факт (ТЖС)"
attr(dataset$kids_visits, "label") <- "Факт (ТЖС/дети)"
attr(dataset$disabled, "label") <- "в т.ч. инвалиды"
attr(dataset$orphans, "label") <- "в т.ч. сироты"
attr(dataset$needy, "label") <- "в т.ч. малообеспеч"
attr(dataset$parents_visits, "label") <- "Факт (ТЖС/сопровождающие)"
attr(dataset$family_non, "label") <- "Недозаезды (ТЖС)"
attr(dataset$kids_non, "label") <- "Недозаезды (ТЖС/дети)"
attr(dataset$parents_non, "label") <- "Недозаезды (ТЖС/сопровождающие)"
attr(dataset$youth_visits, "label") <- "Факт (молодёжный отдых)"
attr(dataset$youth_non, "label") <- "Недозаезды (молодёжный отдых)"
attr(dataset$add_visits, "label") <- "Факт (коммерция)"
attr(dataset$add_kids_visits, "label") <- "из них дети"
attr(dataset$add_parents_visits, "label") <- "из них сопровождающие"
attr(dataset$add_non, "label") <- "Недозаезды (коммерция)"
attr(dataset$add_kids_non, "label") <- "из них дети"
attr(dataset$add_parents_non, "label") <- "из них сопровождающие"
attr(dataset$dep_visits, "label") <- "Факт (ДТСЗН)"
attr(dataset$dep_orphans_u7_visits, "label") <- "из них сироты до 7 лет"
attr(dataset$dep_orphans_o18_visits, "label") <- "из них сироты старше 18 лет"
attr(dataset$dep_educators_visits, "label") <- "Факт (ДТСЗН / педперсонал)"
attr(dataset$dep_non, "label") <- "Недозаезды (ДТСЗН)"
attr(dataset$dep_orphans_u7_non, "label") <- "из них сироты до 7 лет"
attr(dataset$dep_orphans_o18_non, "label") <- "из них сироты старше 18 лет"
attr(dataset$dep_educators_non, "label") <- "Недозаезды (ДТСЗН / педперсонал)"
attr(dataset$visits_total, "label") <- "Факт (всего)"
attr(dataset$mental, "label") <- "из них с ментальными нарушениями"
attr(dataset$muscle_skeleton, "label") <- "из них с нарушениями опорно-двигательного аппарата"
attr(dataset$dysfunction, "label") <- "из них с нарушениями функций систем организма"
attr(dataset$sensorial, "label") <- "из них с сенсорными нарушениями"
attr(dataset$disorders_total, "label") <- "из них всего с нарушениями"
attr(dataset$non_total, "label") <- "Недозаезды (всего)"

attr(dataset$fracture, "label") <- "Переломы"
attr(dataset$brain_damage, "label") <- "Черепно-мозговые травмы"
attr(dataset$dislocation_distortion, "label") <- "Вывихи растяжения"
attr(dataset$ambustion, "label") <- "Термические и химические ожоги"
# attr(dataset$aftertroubles, "label") <- "Последствия травм и отравлений"
attr(dataset$other, "label") <- "Прочие (царапины порезы ушибы)"
# attr(dataset$trm_other, "label") <- "Прочие (царапины порезы ушибы)"
attr(dataset$trm_sum, "label") <- "Всего обращений (травмы)"
attr(dataset$trm_ins, "label") <- "Всего страховых случаев (травмы)"
attr(dataset$infections_infestations, "label") <- "Инфекционные и паразитарные болезни"
attr(dataset$endocrine, "label") <- "Болезни эндокринной системы нарушения обмена веществ"
attr(dataset$nervous, "label") <- "Болезни нервной системы"
attr(dataset$ocular, "label") <- "Болезни глаза"
attr(dataset$otorhinolaryngology, "label") <- "Оториноларигологические болезни"
attr(dataset$heart, "label") <- "Болезни сердечно-сосудистой системы"
attr(dataset$respiratory, "label") <- "Болезни органов дыхания"
attr(dataset$digestive, "label") <- "Болезни органов пищеварения"
attr(dataset$urogenital, "label") <- "Болезни органов мочеполовой системы"
attr(dataset$intoxication, "label") <- "Отравления"
attr(dataset$heat_apoplexy, "label") <- "Тепловые удары"
attr(dataset$acute, "label") <- "Экстренные и неотложные состояния"
attr(dataset$tetter, "label") <- "Болезни кожи неинфекционные"
# attr(dataset$dys_other, "label") <- "Прочие заболевания"
attr(dataset$dys_sum, "label") <- "Всего обращений"
attr(dataset$dys_ins, "label") <- "Всего страховых случаев"
attr(dataset$dys_per_men, "label") <- "Кол-во обращений из-за заболеваний на одного отдыхающего"
attr(dataset$trm_per_men, "label") <- "Кол-во обращений из-за травм на одного отдыхающего"

