attr(dataset$camp_name, "label") <- "Название лагеря"
attr(dataset$date_in, "label") <- "Дата заезда"
attr(dataset$date_out, "label") <- "Дата выезда"
attr(dataset$session, "label") <- "Смена"
attr(dataset$region, "label") <- "Регион"
attr(dataset$duration, "label") <- "Продолжительность смены"
attr(dataset$educators, "label") <- "Кол-во воспитателей"
attr(dataset$fact_vouchers, "label") <- "Факт (ТЖС)"
attr(dataset$disabled, "label") <- "из них инвалиды"
attr(dataset$orphans, "label") <- "из них сироты"
attr(dataset$needy, "label") <- "из них малообеспеч."
attr(dataset$nonarrivals_vouchers, "label") <- "Недозаезды (ТЖС)"
attr(dataset$nonarrivals_by_denial, "label") <- "из них медотводы"
attr(dataset$fact_dep, "label") <- "Факт (ДТСЗН)"
attr(dataset$nonarrivals_dep, "label") <- "Недозаезды (ДТСЗН)"
attr(dataset$fact_total, "label") <- "Факт (всего)"
attr(dataset$mental, "label") <- "из них с ментальными нарушениями"
attr(dataset$muscle_skeleton, "label") <- "из них с нарушениями опорно-двигательного аппарата"
attr(dataset$dysfunction, "label") <- "из них с нарушениями функций систем организма"
attr(dataset$sensorial, "label") <- "из них с сенсорными нарушениями"
attr(dataset$disorders_total, "label") <- "из них всего с нарушениями"
attr(dataset$nonarrivals_total, "label") <- "Недозаезды (всего)"
attr(dataset$non_vouchers, "label") <- "Доля недозаездов (ТЖС)"
attr(dataset$non_department, "label") <- "Доля недозаездов (ДТСЗН)"
attr(dataset$fracture, "label") <- "Переломы"
attr(dataset$brain_damage, "label") <- "Черепно-мозговые травмы"
attr(dataset$dislocation_distortion, "label") <- "Вывихи растяжения"
attr(dataset$ambustion, "label") <- "Термические и химические ожоги"
attr(dataset$aftertroubles, "label") <- "Последствия травм и отравлений"
# attr(dataset$other, "label") <- "Прочие (царапины порезы ушибы)"
attr(dataset$trm_other, "label") <- "Прочие (царапины порезы ушибы)"
attr(dataset$trm_sum, "label") <- "Всего обращений (травмы)"
attr(dataset$trm_ins, "label") <- "Всего страховых случаев (травмы)"
attr(dataset$infections_infestations, "label") <- "Инфекционные и паразитарные болезни"
attr(dataset$endocrine, "label") <- "Болезни эндокринной системы нарушения обмена веществ"
attr(dataset$nervous, "label") <- "Болезни нервной системы"
attr(dataset$ocular, "label") <- "Болезни глаза"
attr(dataset$otorhinolaryngology, "label") <- "Оториноларигологические болезни"
attr(dataset$heart, "label") <- "Болезни сердечно-сосудистой системы"
attr(dataset$respiratory, "label") <- "Болезни органов дыхания"
attr(dataset$digestive, "label") <- "Болезни органов пищеварения"
attr(dataset$urogenital, "label") <- "Болезни органов мочеполовой системы"
attr(dataset$intoxication, "label") <- "Отравления"
attr(dataset$heat_apoplexy, "label") <- "Тепловые удары"
attr(dataset$acute, "label") <- "Экстренные и неотложные состояния"
# attr(dataset$tetter, "label") <- "Болезни кожи неинфекционные"
attr(dataset$dys_other, "label") <- "Прочие заболевания"
attr(dataset$dys_sum, "label") <- "Всего обращений"
attr(dataset$dys_ins, "label") <- "Всего страховых случаев"
attr(dataset$per_department, "label") <- "Доля детей-сирот (ДТСЗН) от кол-ва детей"
attr(dataset$per_disabled, "label") <- "Доля детей детей-инвалидов"
attr(dataset$per_disorders, "label") <- "Доля детей с нарушениями"
attr(dataset$per_mental, "label") <- "Доля детей с ментальными нарушениями"
attr(dataset$per_muscle_skeleton, "label") <- "Доля детей с нарушениями опорно-двигательного аппарата"
attr(dataset$per_dysfunction, "label") <- "Доля детей с нарушениями функций организма"
attr(dataset$per_sensorial, "label") <- "Доля детей с сенсорными нарушениями"
attr(dataset$disorders, "label") <- "Кол-во детей с нарушениями"
attr(dataset$mental, "label") <- "Кол-во детей с ментальными нарушениями"
attr(dataset$muscle_skeleton, "label") <- "Кол-во детей с нарушениями опорно-двигательного аппарата"
attr(dataset$dysfunction, "label") <- "Кол-во детей с нарушениями функций организма"
attr(dataset$sensorial, "label") <- "Кол-во детей с сенсорными нарушениями"
attr(dataset$dys_per_men, "label") <- "Кол-во обращений из-за заболеваний на одного отдыхающего"
attr(dataset$trm_per_men, "label") <- "Кол-во обращений из-за травм на одного отдыхающего"

